prueba de wait deploy

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -45,7 +45,7 @@ jobs:
 
 
 
-  Deploy:
+  Start-Deploy:
     needs: [Linter, Test]
     runs-on: ubuntu-latest
     steps:
@@ -76,10 +76,34 @@ jobs:
         payload: |
           text: "El deploy ha fallado :x: en el repositorio ${{ github.repository }} en la rama ${{ github.ref }} por ${{ github.actor }}."
 
-#agregar esperar el deploy
+  Wait-Deploy:
+    name: Esperar resultado del deploy en Render
+    runs-on: ubuntu-latest
+    needs: [Start-Deploy]
+    if: needs.Start-Deploy.result == 'success'
+    steps:
+      - name: Esperar a que Render termine el deploy
+        run: |
+          deploy_status="pending"
+          while [ "$deploy_status" != "live" ]; do
+            response=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" "https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys")
+            echo "Render API response: $response"
+            deploy_status=$(echo $response | jq -r '.[0].deploy.status')
+            echo "Current deploy status: $deploy_status"
+            if [ "$deploy_status" == "failed" ]; then
+              echo "Deployment failed."
+              exit 1
+            fi
+            sleep 5
+          done
+          echo "Deployment completed successfully."
+        env:
+          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
+
+
       
   E2E_Test:
-    needs: [Deploy]
+    needs: [Wait-Deploy]
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v4
